on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          ISSUE_URL: ${{ https://github.com/sreesar/project.git }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage"
