name: Push File

on: 
 workflow_dispatch: {}
 push:
  branches: 
   - main
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.repo }}
      with:
        source_file: './.github/workflows/test.yml'
        destination_repo: 'sreesar/project'
        destination_folder: 'project/.github/workflows/'
        user_email: 'ninanarmatha0389@gmail.com'
        user_name: 'sreesar'
        #commit_msg: '[GHA] Update the test files.'
