name: docker build image
on:
  workflow_dispatch: {}

  push:
   branches: 
    - main
  pull_request:
   branches: 
    - main
  
jobs:
   build-container:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     
     - name: Login to GitHub Container registry
       uses: docker/login-action@v1
       env:
            GITHUB_USER: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
            registry: ghcr.io
            username: $GITHUB_USER
            password: ${{ secrets.GITHUB_TOKEN }}
     - name: build docker image
       env:
          REGISTRY: ghcr.io
          OWNER: ${{ github.actor }}
          REPOSITORY: myown
          IMAGE_NAME: sampleimage
       run: 
          docker build -t ${{env.REGISTRY}}/${{env.REPOSITORY}}/${{env.IMAGE_NAME}}:1 .

     - name: docker image list
       run:
            docker images
              
     - name: publish a Docker image for ${{ github.repository }}
       uses: macbre/push-to-ghcr@master
       with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }} 
