name: workflow_02
on:
workflow_dispatch: {}
jobs:

  copy-file:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout

      uses: actions/checkout@v2

        - name: Pushes test folder

         uses: GuillaumeFalourd/copy-push-files@v1

      with:

          email: ninanarmatha0389@gmail.com

          name: ${{ github.actor }}

          commit_message: your_message

          target_branch: main

          source_files: ./new/one.txt

          remote_repository: https://github.com/sreesar/mywon

          access_token: ${{ secrets.ACTIONS_KEY }}
